### ISSUE TITLE
#include not recognized

### ISSUE THREAD

**Issue by Mitch9378** [whanwells/language-sqr#2]
# include is not recognized but #Include is.

For some reason this one appears to be case specific.

**Comment by whanwells** [comment]
Yeah, the TextMate bundle I based this on is pretty buggy. I haven't had much time to look at this recently, but will try to get back to it sometime this fall.

**Comment by Mitch9378** [comment]
I will see if I can fix it as well. There is not a lot of support out there for SQR so I am not surprised the TextMate bundle is buggy.
